services:
    _defaults:
        autowire: true
        autoconfigure: true

    bw\ContactBundle\Service\ContactService:
      class: bw\ContactBundle\Service\ContactService
      arguments:
        - "@form.factory"
        - "@swiftmailer.mailer"
        - "@twig"
        - "%contact_recipient%"
